/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package schedulegenerator;

import java.awt.Dimension;
import java.awt.List;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultListModel;

/**
 *
 * @author schneimd
 */
public class Config extends javax.swing.JFrame {

    private boolean firstSelection = true;
    private int numSelected = 0;
    private DefaultListModel[] models;
    
    /**
     * Creates new form.
     */
    public Config() {
        models = new DefaultListModel[7];
        initDyn();
        
        initComponents();
    }
    
    private void initDyn() {
        this.sundayScrollPane = new javax.swing.JScrollPane();
        this.sundayScrollPane.setPreferredSize(new Dimension(185,150));
        this.sundayJobList = new javax.swing.JList();
        this.sundayJobName = new javax.swing.JTextField();
        this.sundayLabel = new javax.swing.JLabel();
        this.sundayAddJob = new javax.swing.JButton();
        this.sundayDeleteJob = new javax.swing.JButton();
        
        this.mondayScrollPane = new javax.swing.JScrollPane();
        this.mondayScrollPane.setPreferredSize(new Dimension(185,150));
        this.mondayJobList = new javax.swing.JList();
        this.mondayJobName = new javax.swing.JTextField();
        this.mondayLabel = new javax.swing.JLabel();
        this.mondayAddJob = new javax.swing.JButton();
        this.mondayDeleteJob = new javax.swing.JButton();
        
        this.tuesdayScrollPane = new javax.swing.JScrollPane();
        this.tuesdayScrollPane.setPreferredSize(new Dimension(185,150));
        this.tuesdayJobList = new javax.swing.JList();
        this.tuesdayJobName = new javax.swing.JTextField();
        this.tuesdayLabel = new javax.swing.JLabel();
        this.tuesdayAddJob = new javax.swing.JButton();
        this.tuesdayDeleteJob = new javax.swing.JButton();
        
        this.wednesdayScrollPane = new javax.swing.JScrollPane();
        this.wednesdayScrollPane.setPreferredSize(new Dimension(185,150));
        this.wednesdayJobList = new javax.swing.JList();
        this.wednesdayJobName = new javax.swing.JTextField();
        this.wednesdayLabel = new javax.swing.JLabel();
        this.wednesdayAddJob = new javax.swing.JButton();
        this.wednesdayDeleteJob = new javax.swing.JButton();
        
        this.thursdayScrollPane = new javax.swing.JScrollPane();
        this.thursdayScrollPane.setPreferredSize(new Dimension(185,150));
        this.thursdayJobList = new javax.swing.JList();
        this.thursdayJobName = new javax.swing.JTextField();
        this.thursdayLabel = new javax.swing.JLabel();
        this.thursdayAddJob = new javax.swing.JButton();
        this.thursdayDeleteJob = new javax.swing.JButton();
        
        this.fridayScrollPane = new javax.swing.JScrollPane();
        this.fridayScrollPane.setPreferredSize(new Dimension(185,150));
        this.fridayJobList = new javax.swing.JList();
        this.fridayJobName = new javax.swing.JTextField();
        this.fridayLabel = new javax.swing.JLabel();
        this.fridayAddJob = new javax.swing.JButton();
        this.fridayDeleteJob = new javax.swing.JButton();
        
        this.saturdayScrollPane = new javax.swing.JScrollPane();
        this.saturdayScrollPane.setPreferredSize(new Dimension(185,150));
        this.saturdayJobList = new javax.swing.JList();
        this.saturdayJobName = new javax.swing.JTextField();
        this.saturdayLabel = new javax.swing.JLabel();
        this.saturdayAddJob = new javax.swing.JButton();
        this.saturdayDeleteJob = new javax.swing.JButton();
        
        mondayTab = new javax.swing.JPanel();
        tuesdayTab = new javax.swing.JPanel();
        wednesdayTab = new javax.swing.JPanel();
        thursdayTab = new javax.swing.JPanel();
        fridayTab = new javax.swing.JPanel();
        saturdayTab = new javax.swing.JPanel();
        sundayTab = new javax.swing.JPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sundayCheck = new javax.swing.JCheckBox();
        wednesdayCheck = new javax.swing.JCheckBox();
        mondayCheck = new javax.swing.JCheckBox();
        tuesdayCheck = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        thursdayCheck = new javax.swing.JCheckBox();
        fridayCheck = new javax.swing.JCheckBox();
        saturdayCheck = new javax.swing.JCheckBox();
        nextButton = new javax.swing.JButton();
        dayTabs = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configuration");
        setPreferredSize(new java.awt.Dimension(801, 87));
        setResizable(false);

        sundayCheck.setText("Sunday");
        sundayCheck.setName("sundayCheck"); // NOI18N
        sundayCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sundayCheckActionPerformed(evt);
            }
        });

        wednesdayCheck.setText("Wednesday");
        wednesdayCheck.setName("wednesdayCheck"); // NOI18N
        wednesdayCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wednesdayCheckActionPerformed(evt);
            }
        });

        mondayCheck.setText("Monday");
        mondayCheck.setName("mondayCheck"); // NOI18N
        mondayCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mondayCheckActionPerformed(evt);
            }
        });

        tuesdayCheck.setText("Tuesday");
        tuesdayCheck.setName("tuesdayCheck"); // NOI18N
        tuesdayCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuesdayCheckActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Days:");

        thursdayCheck.setText("Thursday");
        thursdayCheck.setName("thursdayCheck"); // NOI18N
        thursdayCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thursdayCheckActionPerformed(evt);
            }
        });

        fridayCheck.setText("Friday");
        fridayCheck.setName("fridayCheck"); // NOI18N
        fridayCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fridayCheckActionPerformed(evt);
            }
        });

        saturdayCheck.setText("Saturday");
        saturdayCheck.setName("saturdayCheck"); // NOI18N
        saturdayCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saturdayCheckActionPerformed(evt);
            }
        });

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(sundayCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mondayCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tuesdayCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wednesdayCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(thursdayCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fridayCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saturdayCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nextButton)
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sundayCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fridayCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saturdayCheck, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                        .addComponent(nextButton))
                    .addComponent(wednesdayCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tuesdayCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(thursdayCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mondayCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
            .addComponent(dayTabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dayTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
        );

        dayTabs.getAccessibleContext().setAccessibleName("Days Tab");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void sundayCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sundayCheckActionPerformed
        if(this.sundayCheck.isSelected()) {
            this.numSelected++;
            if(firstSelection) {
                stretch();
            }
            models[0] = new DefaultListModel();
            sundayJobList.setModel(models[0]);
            sundayScrollPane.setViewportView(sundayJobList);

            sundayJobName.setColumns(20);

            sundayLabel.setText("Job Name:");

            sundayAddJob.setText("Add Job");
            sundayAddJob.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    if(!sundayJobName.getText().isEmpty()) {
                        models[0].addElement(sundayJobName.getText());
                        sundayJobList.setModel(models[0]);
                        sundayJobName.setText("");
                    }
                }
            });

            sundayDeleteJob.setText("Delete Job");
            sundayDeleteJob.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    while(!sundayJobList.isSelectionEmpty()) {
                        int n = sundayJobList.getSelectedIndex();
                        models[0].remove(n);
                    }
                    
                }
            });

            javax.swing.GroupLayout sundayTabLayout = new javax.swing.GroupLayout(sundayTab);
            sundayTab.setLayout(sundayTabLayout);
            sundayTabLayout.setHorizontalGroup(
                sundayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sundayTabLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(sundayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(sundayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sundayTabLayout.createSequentialGroup()
                            .addComponent(sundayLabel)
                            .addGroup(sundayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(sundayTabLayout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(sundayAddJob))
                                .addGroup(sundayTabLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sundayJobName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(sundayDeleteJob))
                    .addContainerGap(431, Short.MAX_VALUE))
            );
            sundayTabLayout.setVerticalGroup(
                sundayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sundayTabLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(sundayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(sundayTabLayout.createSequentialGroup()
                            .addGroup(sundayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sundayJobName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sundayLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(sundayAddJob)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sundayDeleteJob))
                        .addComponent(sundayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(25, Short.MAX_VALUE))
            );
            dayTabs.addTab("Sunday", sundayTab);
        } else {
            this.numSelected--;
            stretch();
            this.dayTabs.remove(this.sundayTab);
        }
        
    }//GEN-LAST:event_sundayCheckActionPerformed

    private void mondayCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mondayCheckActionPerformed
        if(this.mondayCheck.isSelected()) {
            this.numSelected++;
            if(firstSelection) {
                stretch();
            }
            models[1] = new DefaultListModel();
            mondayJobList.setModel(models[1]);
            mondayScrollPane.setViewportView(mondayJobList);

            mondayJobName.setColumns(20);

            mondayLabel.setText("Job Name:");

            mondayAddJob.setText("Add Job");
            mondayAddJob.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    if(!mondayJobName.getText().isEmpty()) {
                        models[1].addElement(mondayJobName.getText());
                        mondayJobList.setModel(models[1]);
                        mondayJobName.setText("");
                    }
                }
            });

            mondayDeleteJob.setText("Delete Job");
            mondayDeleteJob.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    while(!mondayJobList.isSelectionEmpty()) {
                        int n = mondayJobList.getSelectedIndex();
                        models[1].remove(n);
                    }
                    
                }
            });

            javax.swing.GroupLayout mondayTabLayout = new javax.swing.GroupLayout(mondayTab);
            mondayTab.setLayout(mondayTabLayout);
            mondayTabLayout.setHorizontalGroup(
                mondayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mondayTabLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(mondayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(mondayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mondayTabLayout.createSequentialGroup()
                            .addComponent(mondayLabel)
                            .addGroup(mondayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(mondayTabLayout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(mondayAddJob))
                                .addGroup(mondayTabLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mondayJobName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(mondayDeleteJob))
                    .addContainerGap(431, Short.MAX_VALUE))
            );
            mondayTabLayout.setVerticalGroup(
                mondayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mondayTabLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(mondayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(mondayTabLayout.createSequentialGroup()
                            .addGroup(mondayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mondayJobName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mondayLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(mondayAddJob)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mondayDeleteJob))
                        .addComponent(mondayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(25, Short.MAX_VALUE))
            );
            dayTabs.addTab("Monday", mondayTab);
        } else {
            this.numSelected--;
            stretch();
            this.dayTabs.remove(this.mondayTab);
        }
                
    }//GEN-LAST:event_mondayCheckActionPerformed

    private void tuesdayCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuesdayCheckActionPerformed
        if(this.tuesdayCheck.isSelected()) {
            this.numSelected++;
            if(firstSelection) {
                stretch();
            }
            models[2] = new DefaultListModel();
            tuesdayJobList.setModel(models[2]);
            tuesdayScrollPane.setViewportView(tuesdayJobList);

            tuesdayJobName.setColumns(20);

            tuesdayLabel.setText("Job Name:");

            tuesdayAddJob.setText("Add Job");
            tuesdayAddJob.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    if(!tuesdayJobName.getText().isEmpty()) {
                        models[2].addElement(tuesdayJobName.getText());
                        tuesdayJobList.setModel(models[2]);
                        tuesdayJobName.setText("");
                    }
                }
            });

            tuesdayDeleteJob.setText("Delete Job");
            tuesdayDeleteJob.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    while(!tuesdayJobList.isSelectionEmpty()) {
                        int n = tuesdayJobList.getSelectedIndex();
                        models[2].remove(n);
                    }
                    
                }
            });

            javax.swing.GroupLayout tuesdayTabLayout = new javax.swing.GroupLayout(tuesdayTab);
            tuesdayTab.setLayout(tuesdayTabLayout);
            tuesdayTabLayout.setHorizontalGroup(
                tuesdayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tuesdayTabLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tuesdayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(tuesdayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tuesdayTabLayout.createSequentialGroup()
                            .addComponent(tuesdayLabel)
                            .addGroup(tuesdayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(tuesdayTabLayout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(tuesdayAddJob))
                                .addGroup(tuesdayTabLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tuesdayJobName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(tuesdayDeleteJob))
                    .addContainerGap(431, Short.MAX_VALUE))
            );
            tuesdayTabLayout.setVerticalGroup(
                tuesdayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tuesdayTabLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(tuesdayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(tuesdayTabLayout.createSequentialGroup()
                            .addGroup(tuesdayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tuesdayJobName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tuesdayLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tuesdayAddJob)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tuesdayDeleteJob))
                        .addComponent(tuesdayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(25, Short.MAX_VALUE))
            );
            dayTabs.addTab("Tuesday", tuesdayTab);
        } else {
            this.numSelected--;
            stretch();
            this.dayTabs.remove(tuesdayTab);
        }
    }//GEN-LAST:event_tuesdayCheckActionPerformed

    private void wednesdayCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wednesdayCheckActionPerformed
        if(this.wednesdayCheck.isSelected()) {
            this.numSelected++;
            if(firstSelection) {
                stretch();
            }
            models[3] = new DefaultListModel();
            wednesdayJobList.setModel(models[3]);
            wednesdayScrollPane.setViewportView(wednesdayJobList);

            wednesdayJobName.setColumns(20);

            wednesdayLabel.setText("Job Name:");

            wednesdayAddJob.setText("Add Job");
            wednesdayAddJob.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    if(!wednesdayJobName.getText().isEmpty()) {
                        models[3].addElement(wednesdayJobName.getText());
                        wednesdayJobList.setModel(models[3]);
                        wednesdayJobName.setText("");
                    }
                }
            });

            wednesdayDeleteJob.setText("Delete Job");
            wednesdayDeleteJob.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    while(!wednesdayJobList.isSelectionEmpty()) {
                        int n = wednesdayJobList.getSelectedIndex();
                        models[3].remove(n);
                    }
                    
                }
            });

            javax.swing.GroupLayout wednesdayTabLayout = new javax.swing.GroupLayout(wednesdayTab);
            wednesdayTab.setLayout(wednesdayTabLayout);
            wednesdayTabLayout.setHorizontalGroup(
                wednesdayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(wednesdayTabLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(wednesdayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(wednesdayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(wednesdayTabLayout.createSequentialGroup()
                            .addComponent(wednesdayLabel)
                            .addGroup(wednesdayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(wednesdayTabLayout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(wednesdayAddJob))
                                .addGroup(wednesdayTabLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(wednesdayJobName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(wednesdayDeleteJob))
                    .addContainerGap(431, Short.MAX_VALUE))
            );
            wednesdayTabLayout.setVerticalGroup(
                wednesdayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(wednesdayTabLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(wednesdayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(wednesdayTabLayout.createSequentialGroup()
                            .addGroup(wednesdayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(wednesdayJobName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(wednesdayLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(wednesdayAddJob)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(wednesdayDeleteJob))
                        .addComponent(wednesdayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(25, Short.MAX_VALUE))
            );
            dayTabs.addTab("Wednesday", wednesdayTab);
        } else {
            this.numSelected--;
            stretch();
            this.dayTabs.remove(this.wednesdayTab);
        }
        
    }//GEN-LAST:event_wednesdayCheckActionPerformed

    private void thursdayCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thursdayCheckActionPerformed
        if(this.thursdayCheck.isSelected()) {
            this.numSelected++;
            if(firstSelection) {
                stretch();
            }
            models[4] = new DefaultListModel();
            thursdayJobList.setModel(models[4]);
            thursdayScrollPane.setViewportView(thursdayJobList);

            thursdayJobName.setColumns(20);

            thursdayLabel.setText("Job Name:");

            thursdayAddJob.setText("Add Job");
            thursdayAddJob.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    if(!thursdayJobName.getText().isEmpty()) {
                        models[4].addElement(thursdayJobName.getText());
                        thursdayJobList.setModel(models[4]);
                        thursdayJobName.setText("");
                    }
                }
            });

            thursdayDeleteJob.setText("Delete Job");
            thursdayDeleteJob.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    while(!thursdayJobList.isSelectionEmpty()) {
                        int n = thursdayJobList.getSelectedIndex();
                        models[4].remove(n);
                    }
                    
                }
            });

            javax.swing.GroupLayout thursdayTabLayout = new javax.swing.GroupLayout(thursdayTab);
            thursdayTab.setLayout(thursdayTabLayout);
            thursdayTabLayout.setHorizontalGroup(
                thursdayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(thursdayTabLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(thursdayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(thursdayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(thursdayTabLayout.createSequentialGroup()
                            .addComponent(thursdayLabel)
                            .addGroup(thursdayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(thursdayTabLayout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(thursdayAddJob))
                                .addGroup(thursdayTabLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(thursdayJobName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(thursdayDeleteJob))
                    .addContainerGap(431, Short.MAX_VALUE))
            );
            thursdayTabLayout.setVerticalGroup(
                thursdayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(thursdayTabLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(thursdayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(thursdayTabLayout.createSequentialGroup()
                            .addGroup(thursdayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(thursdayJobName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(thursdayLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(thursdayAddJob)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(thursdayDeleteJob))
                        .addComponent(thursdayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(25, Short.MAX_VALUE))
            );
            dayTabs.addTab("Thursday", thursdayTab);
        } else {
            this.numSelected--;
            stretch();
            this.dayTabs.remove(this.thursdayTab);
        }
        
    }//GEN-LAST:event_thursdayCheckActionPerformed

    private void fridayCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fridayCheckActionPerformed
       if(this.fridayCheck.isSelected()) {
            this.numSelected++;
            if(firstSelection) {
                stretch();
            }
            models[5] = new DefaultListModel();
            fridayJobList.setModel(models[5]);
            fridayScrollPane.setViewportView(fridayJobList);

            fridayJobName.setColumns(20);

            fridayLabel.setText("Job Name:");

            fridayAddJob.setText("Add Job");
            fridayAddJob.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    if(!fridayJobName.getText().isEmpty()) {
                        models[5].addElement(fridayJobName.getText());
                        fridayJobList.setModel(models[5]);
                        fridayJobName.setText("");
                    }
                }
            });

            fridayDeleteJob.setText("Delete Job");
            fridayDeleteJob.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    while(!fridayJobList.isSelectionEmpty()) {
                        int n = fridayJobList.getSelectedIndex();
                        models[5].remove(n);
                    }
                    
                }
            });

            javax.swing.GroupLayout fridayTabLayout = new javax.swing.GroupLayout(fridayTab);
            fridayTab.setLayout(fridayTabLayout);
            fridayTabLayout.setHorizontalGroup(
                fridayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fridayTabLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(fridayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(fridayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(fridayTabLayout.createSequentialGroup()
                            .addComponent(fridayLabel)
                            .addGroup(fridayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(fridayTabLayout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(fridayAddJob))
                                .addGroup(fridayTabLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fridayJobName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(fridayDeleteJob))
                    .addContainerGap(431, Short.MAX_VALUE))
            );
            fridayTabLayout.setVerticalGroup(
                fridayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fridayTabLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(fridayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(fridayTabLayout.createSequentialGroup()
                            .addGroup(fridayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fridayJobName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fridayLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fridayAddJob)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fridayDeleteJob))
                        .addComponent(fridayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(25, Short.MAX_VALUE))
            );
            dayTabs.addTab("Friday", fridayTab);
        } else {
            this.numSelected--;
            stretch();
            this.dayTabs.remove(this.fridayTab);
        }
        
    }//GEN-LAST:event_fridayCheckActionPerformed

    private void saturdayCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saturdayCheckActionPerformed
        if(this.saturdayCheck.isSelected()) {
            this.numSelected++;
            if(firstSelection) {
                stretch();
            }
            models[6] = new DefaultListModel();
            saturdayJobList.setModel(models[6]);
            saturdayScrollPane.setViewportView(saturdayJobList);

            saturdayJobName.setColumns(20);

            saturdayLabel.setText("Job Name:");

            saturdayAddJob.setText("Add Job");
            saturdayAddJob.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    if(!saturdayJobName.getText().isEmpty()) {
                        models[6].addElement(saturdayJobName.getText());
                        saturdayJobList.setModel(models[6]);
                        saturdayJobName.setText("");
                    }
                }
            });

            saturdayDeleteJob.setText("Delete Job");
            saturdayDeleteJob.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    while(!saturdayJobList.isSelectionEmpty()) {
                        int n = saturdayJobList.getSelectedIndex();
                        models[6].remove(n);
                    }
                    
                }
            });

            javax.swing.GroupLayout saturdayTabLayout = new javax.swing.GroupLayout(saturdayTab);
            saturdayTab.setLayout(saturdayTabLayout);
            saturdayTabLayout.setHorizontalGroup(
                saturdayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(saturdayTabLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(saturdayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(saturdayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(saturdayTabLayout.createSequentialGroup()
                            .addComponent(saturdayLabel)
                            .addGroup(saturdayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(saturdayTabLayout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(saturdayAddJob))
                                .addGroup(saturdayTabLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(saturdayJobName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(saturdayDeleteJob))
                    .addContainerGap(431, Short.MAX_VALUE))
            );
            saturdayTabLayout.setVerticalGroup(
                saturdayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(saturdayTabLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(saturdayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(saturdayTabLayout.createSequentialGroup()
                            .addGroup(saturdayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(saturdayJobName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(saturdayLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(saturdayAddJob)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saturdayDeleteJob))
                        .addComponent(saturdayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(25, Short.MAX_VALUE))
            );
            dayTabs.addTab("Saturday", saturdayTab);
        } else {
            this.numSelected--;
            stretch();
            this.dayTabs.remove(this.saturdayTab);
        }
    }//GEN-LAST:event_saturdayCheckActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        ArrayList<Day> days = new ArrayList<Day>();
    	//if(this.sundayCheck.isSelected())
//        {
//    		ArrayList<Object> sun = new ArrayList<Object>();
//    		List<Object> jobs = Arrays.asList(this.models[0].toArray());
//    		sun.addAll(jobs);
//        	days.add(new Day("Sunday",sun));
//        }
//    	if(this.mondayCheck.isSelected())
//        {
//    		ArrayList<Object> mon = new ArrayList<Object>();
//    		List<Object> jobs = Arrays.asList(this.models[1].toArray());
//    		mon.addAll(jobs);
//        	days.add(new Day("Monday",mon));
//        }
//    	if(this.tuesdayCheck.isSelected())
//        {
//    		ArrayList<Object> tue = new ArrayList<Object>();
//    		List<Object> jobs = Arrays.asList(this.models[2].toArray());
//    		tue.addAll(jobs);
//        	days.add(new Day("Tuesday",tue));
//        }
//    	if(this.wednesdayCheck.isSelected())
//        {
//    		ArrayList<Object> wed = new ArrayList<Object>();
//    		List<Object> jobs = Arrays.asList(this.models[3].toArray());
//    		wed.addAll(jobs);
//        	days.add(new Day("Wednesday",wed));
//        }
//    	if(this.thursdayCheck.isSelected())
//        {
//    		ArrayList<Object> thu = new ArrayList<Object>();
//    		List<Object> jobs = Arrays.asList(this.models[4].toArray());
//    		thu.addAll(jobs);
//        	days.add(new Day("Thursday",thu));
//        }
//    	if(this.fridayCheck.isSelected())
//        {
//    		ArrayList<Object> fri = new ArrayList<Object>();
//    		List<Object> jobs = Arrays.asList(this.models[5].toArray());
//    		fri.addAll(jobs);
//        	days.add(new Day("Friday",fri));
//        }
//    	if(this.saturdayCheck.isSelected())
//        {
//    		ArrayList<Object> sat = new ArrayList<Object>();
//    		List<Object> jobs = Arrays.asList(this.models[6].toArray());
//    		sat.addAll(jobs);
//        	days.add(new Day("Saturday",sat));
//        }
//    	Main.setDays(days);
    	Main.toggleWorkerSetup();
    	Main.toggleConfig();
    }//GEN-LAST:event_nextButtonActionPerformed
    
    
    private void stretch() {
        if(this.numSelected > 0) {
            this.setSize(801, 290);
            firstSelection = false;
        } else {
            this.setSize(801, 87);
            firstSelection = true;
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Config().setVisible(true);
            }
        });
    }
    
    private javax.swing.JScrollPane sundayScrollPane;
    private javax.swing.JButton sundayAddJob;
    private javax.swing.JButton sundayDeleteJob;
    private javax.swing.JList sundayJobList;
    private javax.swing.JTextField sundayJobName;
    private javax.swing.JLabel sundayLabel;
    private javax.swing.JPanel sundayTab;
    
    private javax.swing.JScrollPane mondayScrollPane;
    private javax.swing.JButton mondayAddJob;
    private javax.swing.JButton mondayDeleteJob;
    private javax.swing.JList mondayJobList;
    private javax.swing.JTextField mondayJobName;
    private javax.swing.JLabel mondayLabel;
    private javax.swing.JPanel mondayTab;
    
    private javax.swing.JScrollPane tuesdayScrollPane;
    private javax.swing.JButton tuesdayAddJob;
    private javax.swing.JButton tuesdayDeleteJob;
    private javax.swing.JList tuesdayJobList;
    private javax.swing.JTextField tuesdayJobName;
    private javax.swing.JLabel tuesdayLabel;
    private javax.swing.JPanel tuesdayTab;
    
    private javax.swing.JScrollPane wednesdayScrollPane;
    private javax.swing.JButton wednesdayAddJob;
    private javax.swing.JButton wednesdayDeleteJob;
    private javax.swing.JList wednesdayJobList;
    private javax.swing.JTextField wednesdayJobName;
    private javax.swing.JLabel wednesdayLabel;
    private javax.swing.JPanel wednesdayTab;
    
    private javax.swing.JScrollPane thursdayScrollPane;
    private javax.swing.JButton thursdayAddJob;
    private javax.swing.JButton thursdayDeleteJob;
    private javax.swing.JList thursdayJobList;
    private javax.swing.JTextField thursdayJobName;
    private javax.swing.JLabel thursdayLabel;
    private javax.swing.JPanel thursdayTab;
    
    private javax.swing.JScrollPane fridayScrollPane;
    private javax.swing.JButton fridayAddJob;
    private javax.swing.JButton fridayDeleteJob;
    private javax.swing.JList fridayJobList;
    private javax.swing.JTextField fridayJobName;
    private javax.swing.JLabel fridayLabel;
    private javax.swing.JPanel fridayTab;
    
    private javax.swing.JScrollPane saturdayScrollPane;
    private javax.swing.JButton saturdayAddJob;
    private javax.swing.JButton saturdayDeleteJob;
    private javax.swing.JList saturdayJobList;
    private javax.swing.JTextField saturdayJobName;
    private javax.swing.JLabel saturdayLabel;
    private javax.swing.JPanel saturdayTab;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane dayTabs;
    private javax.swing.JCheckBox fridayCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox mondayCheck;
    private javax.swing.JButton nextButton;
    private javax.swing.JCheckBox saturdayCheck;
    private javax.swing.JCheckBox sundayCheck;
    private javax.swing.JCheckBox thursdayCheck;
    private javax.swing.JCheckBox tuesdayCheck;
    private javax.swing.JCheckBox wednesdayCheck;
    // End of variables declaration//GEN-END:variables
}
